### ISSUE TITLE
`ValueError: invalid literal for int() with base 10` when running `browse` command

### ISSUE THREAD

**Issue by simeoncarstens** [desgeeko/pdfsyntax#3]
On the same (random) [ebook](https://github.com/shahumar/Free-Machine-Learning-Books/blob/master/book/A%20Course%20in%20Machine%20Learning.pdf) as in #2, I get the following error when running `python3 -m pdfsyntax browse filename.pdf`:
```
Traceback (most recent call last):
  File "/nix/store/x7agqy4zr8na6rc7252avhwppgfylz33-python3-3.10.13/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/nix/store/x7agqy4zr8na6rc7252avhwppgfylz33-python3-3.10.13/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/simeon/test/penv/lib/python3.10/site-packages/pdfsyntax/__main__.py", line 4, in <module>
    main()
  File "/home/simeon/test/penv/lib/python3.10/site-packages/pdfsyntax/cli.py", line 22, in main
    browse(args.filename)
  File "/home/simeon/test/penv/lib/python3.10/site-packages/pdfsyntax/cli.py", line 247, in browse
    print(build_html(file_seq, pos_index, nb_ver, filename, fdata(0, 8)[0]))
  File "/home/simeon/test/penv/lib/python3.10/site-packages/pdfsyntax/display.py", line 100, in build_html
    page += follow_obj(obj, mini_index, pos_index)
  File "/home/simeon/test/penv/lib/python3.10/site-packages/pdfsyntax/display.py", line 203, in follow_obj
    ret += f'  {name:{NAME_MAX_WIDTH}}<a class="obj-link" href="#obj{pos_index[int(value)]}">{value}</a>\n'                
ValueError: invalid literal for int() with base 10: '<a href="#obj566.0.0"><span class="obj-link">566 0 R</span></a>'
```

**Comment by desgeeko** [comment]
Thank you for your bug report!
Indirectly fixed with html display refactoring in commit d1daa2a047b546f39b4f765a54c86593350f73e6
Regards
